const questions = [
  {question:"Quale di questi elementi è parte di un diagramma dei casi d’uso?",options:["Attore","Classe","Metodo","Nodo di attività"],correct:"Attore"},
  {question:"Cosa indicano le frecce in un diagramma di sequenza?",options:["Eventi inviati da un oggetto ad un altro","Relazioni tra classi","Stati del sistema","Dipendenze tra moduli"],correct:"Eventi inviati da un oggetto ad un altro"},
  {question:"Che tipo di relazione può esistere tra un attore e un caso d’uso?",options:["Associazione","Ereditarietà","Composizione","Aggregazione"],correct:"Associazione"},
  {question:"Un prototipo viene sviluppato per:",options:["Interagire con il committente per convalidare i requisiti","Scrivere codice finale","Ottimizzare prestazioni","Distribuire il sistema"],correct:"Interagire con il committente per convalidare i requisiti"},
  {question:"Qual è la parola chiave per dichiarare un'interfaccia in Java?",options:["interface","class","extends","implements"],correct:"interface"},
  {question:"Quale dei seguenti non è un concetto OOP?",options:["Compilazione","Incapsulamento","Ereditarietà","Polimorfismo"],correct:"Compilazione"},
  {question:"Quando viene determinato l’overloading?",options:["A tempo di compilazione","A runtime","Durante il deploy","Durante il testing"],correct:"A tempo di compilazione"},
  {question:"Il diagramma di attività:",options:["Modella una sequenza di azioni","Descrive database","Mostra memoria","Gestisce thread"],correct:"Modella una sequenza di azioni"},
  {question:"Qual è il ruolo del costruttore?",options:["Inizializzare l'oggetto","Distruggere oggetti","Gestire errori","Stampare output"],correct:"Inizializzare l'oggetto"},
  {question:"Output: int x=5; int y=x++;",options:["5","6","0","Errore"],correct:"5"},
  {question:"Output while x<4",options:["1 2 3","1 2 3 4","0 1 2 3","Errore"],correct:"1 2 3"},
  {question:"Classe astratta vs interfaccia:",options:["Classe astratta può avere costruttori","Interfaccia ha costruttori","Sono identiche","Classe astratta non ha metodi"],correct:"Classe astratta può avere costruttori"},
  {question:"Pattern Singleton:",options:["Una sola istanza","Più oggetti","Gestione memoria","Thread"],correct:"Una sola istanza"},
  {question:"OCL significa:",options:["Object Constraint Language","Object Class Logic","Operation Layer","Control Language"],correct:"Object Constraint Language"},
  {question:"super in Java:",options:["Richiama superclasse","Crea oggetto","Gestisce memoria","Dichiara variabile"],correct:"Richiama superclasse"},
  {question:"Email è:",options:["Asincrona","Sincrona","Locale","Diretta"],correct:"Asincrona"},
  {question:"Non UML:",options:["stateflow diagram","sequence","class","use case"],correct:"stateflow diagram"},
  {question:"Naming classi:",options:["PascalCase","snake_case","lowercase","UPPERCASE"],correct:"PascalCase"},
  {question:"Nodo decisione:",options:["Rombo","Cerchio","Quadrato","Triangolo"],correct:"Rombo"},
  {question:"final:",options:["Costante","Metodo","Classe","Variabile"],correct:"Costante"},
  {question:"break:",options:["Esce dal ciclo","Ripete ciclo","Crea variabile","Gestisce memoria"],correct:"Esce dal ciclo"},
  {question:"Incapsulamento:",options:["Protegge dati","Ereditarietà","Override","Loop"],correct:"Protegge dati"},
  {question:"Ereditarietà:",options:["Riutilizzo codice","Memoria","Oggetti","Loop"],correct:"Riutilizzo codice"},
  {question:"10+20:",options:["30","10","20","Errore"],correct:"30"},
  {question:"JVM:",options:["Esegue bytecode","Compila codice","Rete","Classi"],correct:"Esegue bytecode"},
  {question:"Commento Java:",options:["//","#","<!-- -->","**"],correct:"//"},
  {question:"do-while:",options:["Esegue almeno una volta","Mai","Uguale while","Non esiste"],correct:"Esegue almeno una volta"},
  {question:"Iterator:",options:["Accesso sequenziale","Memoria","Oggetti","Thread"],correct:"Accesso sequenziale"},
  {question:"private:",options:["Solo classe","Tutti","Package","Sottoclassi"],correct:"Solo classe"},
  {question:"Composite:",options:["Gerarchie","DB","Thread","UI"],correct:"Gerarchie"},
  {question:"State:",options:["Cambia comportamento","Oggetti","Memoria","Loop"],correct:"Cambia comportamento"},
  {question:"Array errore:",options:["Indice fuori limite","Null","Casting","Loop"],correct:"Indice fuori limite"},
  {question:"Gantt:",options:["Deliverable","Classi","Oggetti","Metodi"],correct:"Deliverable"},
  {question:"Singleton keyword:",options:["static","public","final","abstract"],correct:"static"},
  {question:"(int)7.9:",options:["7","8","7.9","Errore"],correct:"7"},
  {question:"Diagramma classi:",options:["Descrive oggetti","Esegue codice","Memoria","Rete"],correct:"Descrive oggetti"},
  {question:"Iterativo vs incrementale:",options:["Iterativo raffina","Uguali","Solo uno","Non esistono"],correct:"Iterativo raffina"},
  {question:"Spirale:",options:["Gestione rischi","Solo coding","Testing","Design"],correct:"Gestione rischi"},
  {question:"JAVA_HOME:",options:["Path JDK","Classe","Metodo","Compilatore"],correct:"Path JDK"},
  {question:"PATH:",options:["Trova java","Esegue codice","Crea classi","Memoria"],correct:"Trova java"}
  ,
{question:"Qual è l'output? boolean x=true; System.out.println(!x);",options:["false","true","1","0"],correct:"false"},
{question:"for(int i=0;i<3;i++) print(i)",options:["0 1 2","1 2 3","0 1 2 3","Errore"],correct:"0 1 2"},
{question:"a=3 b=4 print a*b",options:["12","7","1","Errore"],correct:"12"},
{question:"Classe astratta può avere metodi concreti?",options:["Si","No","Solo statici","Solo privati"],correct:"Si"},
{question:"Task in progetto:",options:["Lavoro da svolgere","Errore","Classe","Metodo"],correct:"Lavoro da svolgere"},
{question:"Schedule:",options:["Tempo pianificato","Codice","Classe","Memoria"],correct:"Tempo pianificato"},
{question:"Rettangolo sotto oggetto in sequenza:",options:["Attivazione","Classe","Metodo","Stato"],correct:"Attivazione"},
{question:"Sequence diagram elementi:",options:["Oggetti e messaggi","Classi","DB","Variabili"],correct:"Oggetti e messaggi"},
{question:"Singleton scenario:",options:["Una sola risorsa","Molti oggetti","Thread","DB"],correct:"Una sola risorsa"},
{question:"super keyword:",options:["Richiama superclasse","Crea oggetto","Dichiara","Loop"],correct:"Richiama superclasse"},
{question:"Errore while counter:",options:["Nessun errore","Loop infinito","Errore sintassi","Null"],correct:"Nessun errore"},
{question:"Diagramma deployment:",options:["Parallelepipedo","Cerchio","Linea","Rombo"],correct:"Parallelepipedo"},
{question:"Walkthrough:",options:["Revisione qualità","Codice","Errore","Deploy"],correct:"Revisione qualità"},
{question:"abstract:",options:["Classe/metodo astratto","Loop","Variabile","Errore"],correct:"Classe/metodo astratto"},
{question:"Nodo decisione:",options:["Rombo","Cerchio","Linea","Quadrato"],correct:"Rombo"},
{question:"Time keeper:",options:["Gestisce tempo","Scrive","Codifica","Test"],correct:"Gestisce tempo"},
{question:"break:",options:["Esce ciclo","Ripete","Crea","Errore"],correct:"Esce ciclo"},
{question:"Pseudostato iniziale:",options:["Disco pieno","Cerchio vuoto","Linea","Rombo"],correct:"Disco pieno"},
{question:"PERT percorso critico:",options:["Più lungo","Più corto","Random","Errore"],correct:"Più lungo"},
{question:"Linea vita:",options:["Diagramma sequenza","Classe","Metodo","DB"],correct:"Diagramma sequenza"},
{question:"Ereditarietà:",options:["Riutilizzo codice","Loop","Errore","Memoria"],correct:"Riutilizzo codice"},
{question:"Output 10+20:",options:["30","20","10","Errore"],correct:"30"},
{question:"Classe UML:",options:["Rettangolo compartimenti","Cerchio","Linea","Triangolo"],correct:"Rettangolo compartimenti"},
{question:"Package diagram:",options:["Rettangolo linguetta","Cerchio","Linea","Quadrato"],correct:"Rettangolo linguetta"},
{question:"Attività UML:",options:["Workflow","Classe","Metodo","DB"],correct:"Workflow"},
{question:"while vs do:",options:["do almeno una volta","Uguali","Mai","Errore"],correct:"do almeno una volta"},
{question:"State pattern:",options:["Cambio comportamento","DB","Memoria","Thread"],correct:"Cambio comportamento"},
{question:"Array errore:",options:["Indice fuori","Null","Loop","Cast"],correct:"Indice fuori"},
{question:"Iterator:",options:["Accesso sequenziale","DB","Thread","Classe"],correct:"Accesso sequenziale"},
{question:"Messaggio asincrono:",options:["Non attende risposta","Attende","Blocca","Errore"],correct:"Non attende risposta"},
{question:"Messaggio sincrono:",options:["Attende risposta","Non attende","Errore","Loop"],correct:"Attende risposta"},
{question:"private:",options:["Solo classe","Tutti","Package","Sub"],correct:"Solo classe"},
{question:"Foglia composite:",options:["Elemento senza figli","Radice","Loop","Errore"],correct:"Elemento senza figli"},
{question:"Composite:",options:["Gerarchie","DB","Thread","Loop"],correct:"Gerarchie"},
{question:"Diagramma stato:",options:["Stati sistema","Classe","Metodo","DB"],correct:"Stati sistema"},
{question:"JAVA_HOME:",options:["Path JDK","Classe","Metodo","Errore"],correct:"Path JDK"},
{question:"PATH:",options:["Trova compiler","Memoria","Classe","Errore"],correct:"Trova compiler"}
  ,
{question:"Qual è lo scopo principale dell'incapsulamento?",options:["Proteggere l'integrità dei dati","Creare oggetti","Gestire thread","Ottimizzare codice"],correct:"Proteggere l'integrità dei dati"},
{question:"Polimorfismo dinamico:",options:["Basato sul tipo reale oggetto","Tipo variabile","Statico","Errore"],correct:"Basato sul tipo reale oggetto"},
{question:"Messaggio trovato (found message):",options:["Da sorgente esterna","Da classe","Da metodo","Interno"],correct:"Da sorgente esterna"},
{question:"Triangolo nero associazione:",options:["Direzione lettura","Classe","Metodo","Errore"],correct:"Direzione lettura"},
{question:"Ciclo vita software termina:",options:["Quando non usato","Quando compilato","Quando scritto","Mai"],correct:"Quando non usato"},
{question:"Modello spirale:",options:["Gestione rischi esplicita","Solo coding","Solo test","Nessun rischio"],correct:"Gestione rischi esplicita"},
{question:"Metodo void:",options:["Non restituisce valore","Restituisce int","Restituisce boolean","Errore"],correct:"Non restituisce valore"},
{question:"Operatore uguaglianza Java:",options:["==","=","!=","<="],correct:"=="},
{question:"Operatore ref in sequenza:",options:["Includere diagramma","Loop","Errore","Classe"],correct:"Includere diagramma"},
{question:"Molteplicità 1..3:",options:["Min 1 max 3","Sempre 3","Sempre 1","Errore"],correct:"Min 1 max 3"},
{question:"Oggetto UML:",options:["Nome sottolineato","Rettangolo","Cerchio","Linea"],correct:"Nome sottolineato"},
{question:"Design pattern:",options:["Soluzione riutilizzabile","Classe","Metodo","Errore"],correct:"Soluzione riutilizzabile"},
{question:"Identificatori Java:",options:["Lettera o underscore","Numero","Simbolo","Spazio"],correct:"Lettera o underscore"},
{question:"Visibilità protetta:",options:["#","+","-","*"],correct:"#"},
{question:"Visibilità privata:",options:["-","#","+","*"],correct:"-"},
{question:"Visibilità pubblica:",options:["+","-","#","*"],correct:"+"},
{question:"Navigabilità associazione:",options:["Chi accede a chi","Classe","Metodo","Errore"],correct:"Chi accede a chi"},
{question:"Caso d’uso descrive:",options:["Azioni attore","Classe","Metodo","Errore"],correct:"Azioni attore"},
{question:"Messaggio perduto:",options:["Senza destinatario","Con destinatario","Errore","Loop"],correct:"Senza destinatario"},
{question:"Ristrutturazione:",options:["Non richiesta sviluppo","Fase principale","Metodo","Errore"],correct:"Non richiesta sviluppo"},
{question:"Valore default attributo:",options:["Valore iniziale","Random","Null sempre","Errore"],correct:"Valore iniziale"},
{question:"Sviluppo iterativo:",options:["Versioni successive","Unica versione","Statico","Errore"],correct:"Versioni successive"},
{question:"Incrementale vs iterativo:",options:["Incrementale aggiunge","Uguali","Solo uno","Errore"],correct:"Incrementale aggiunge"},
{question:"Gestione rischi spirale:",options:["Esplicita","Assente","Casuale","Errore"],correct:"Esplicita"},
{question:"Periodo attività oggetto:",options:["Linea vita","Classe","Metodo","Errore"],correct:"Linea vita"},
{question:"String package Java:",options:["java.lang","java.sql","java.io","java.net"],correct:"java.lang"},
{question:"Alpha e Beta test:",options:["Test sistema","Unit test","Loop","Errore"],correct:"Test sistema"},
{question:"Metodo vs operazione:",options:["Metodo implementa","Uguali","Diversi","Errore"],correct:"Metodo implementa"},
{question:"Classe senza dettagli UML:",options:["Nessun dettaglio","Errore","Metodo","Classe"],correct:"Nessun dettaglio"},
{question:"Attività riflessiva:",options:["Stessa classe","Diversa classe","Errore","Loop"],correct:"Stessa classe"},
{question:"Nome attributo:",options:["Significativo","Random","Numero","Errore"],correct:"Significativo"},
{question:"Classe UML rappresentazione:",options:["3 sezioni","2 sezioni","1 sezione","Errore"],correct:"3 sezioni"},
{question:"Ereditarietà dinamica:",options:["Runtime corretto","Compile","Errore","Statico"],correct:"Runtime corretto"},
{question:"Diagramma stato UML:",options:["Evoluzione stati","Classe","Metodo","Errore"],correct:"Evoluzione stati"},
{question:"Found message:",options:["Da esterno","Interno","Errore","Loop"],correct:"Da esterno"},
{question:"Primo messaggio trovato:",options:["Fonte esterna","Classe","Metodo","Errore"],correct:"Fonte esterna"},
{question:"for loop output:",options:["1-1 2-1","1-2 2-2","Errore","Loop"],correct:"1-1 2-1"}
  ,
{question:"Qual è il ruolo del minute taker?",options:["Scrivere verbale","Gestire tempo","Codificare","Testare"],correct:"Scrivere verbale"},
{question:"Qual è la funzione del liaison?",options:["Trasferire informazioni","Codificare","Testare","Gestire memoria"],correct:"Trasferire informazioni"},
{question:"Qual è il vantaggio comunicazione faccia a faccia?",options:["Rapida ed economica","Costosa","Lenta","Inutile"],correct:"Rapida ed economica"},
{question:"Videoconferenza è:",options:["Sincrona","Asincrona","Locale","Distribuita"],correct:"Sincrona"},
{question:"Vista UML:",options:["Mostra aspetti selezionati","Classe","Metodo","Errore"],correct:"Mostra aspetti selezionati"},
{question:"Astrazione UML:",options:["Classificazione fenomeni","Classe","Metodo","Errore"],correct:"Classificazione fenomeni"},
{question:"Iterator non vantaggio:",options:["Operazioni parallele","Accesso sequenziale","Incapsulamento","Semplicità"],correct:"Operazioni parallele"},
{question:"Singleton scopo:",options:["Una sola istanza globale","Molte istanze","Thread","DB"],correct:"Una sola istanza globale"},
{question:"Java indipendente:",options:["Portabilità","Velocità","Memoria","Errore"],correct:"Portabilità"},
{question:"Classe astratta:",options:["Non istanziabile","Sempre istanziabile","Statica","Errore"],correct:"Non istanziabile"},
{question:"Bytecode eseguito da:",options:["JVM","JDK","IDE","Compilatore"],correct:"JVM"},
{question:"switch break:",options:["Termina case","Loop","Errore","Variabile"],correct:"Termina case"},
{question:"this keyword:",options:["Riferimento oggetto","Classe","Metodo","Errore"],correct:"Riferimento oggetto"},
{question:"Iterator scopo:",options:["Accesso senza esporre struttura","Memoria","Thread","Errore"],correct:"Accesso senza esporre struttura"},
{question:"Messaggio asincrono UML:",options:["Non attende risposta","Attende risposta","Errore","Loop"],correct:"Non attende risposta"},
{question:"Messaggio sincrono UML:",options:["Attende risposta","Non attende","Errore","Loop"],correct:"Attende risposta"},
{question:"Modificatore private:",options:["Solo classe","Tutti","Package","Sub"],correct:"Solo classe"},
{question:"Foglia Composite:",options:["Elemento senza figli","Radice","Errore","Loop"],correct:"Elemento senza figli"},
{question:"Composite vantaggio:",options:["Gerarchie oggetti","DB","Thread","Errore"],correct:"Gerarchie oggetti"},
{question:"Use case NON corretto:",options:["Mostra implementazione","Mostra attori","Mostra azioni","Errore"],correct:"Mostra implementazione"},
{question:"Pattern State non adatto:",options:["Troppi stati complessi","Pochi stati","Errore","Loop"],correct:"Troppi stati complessi"},
{question:"if(false) output:",options:["False","True","Errore","Null"],correct:"False"},
{question:"Gantt barre:",options:["Deliverable","Classi","Metodo","Errore"],correct:"Deliverable"},
{question:"Nodo ricezione attività:",options:["Rettangolo con punta","Cerchio","Linea","Errore"],correct:"Rettangolo con punta"},
{question:"Diagramma stato:",options:["Evoluzione stati","Classe","Metodo","Errore"],correct:"Evoluzione stati"},
{question:"PATH Java:",options:["Trova compilatore","Memoria","Classe","Errore"],correct:"Trova compilatore"},
{question:"JAVA_HOME:",options:["Directory JDK","Classe","Metodo","Errore"],correct:"Directory JDK"},
{question:"Waterfall problema:",options:["Poca interazione utente","Troppo agile","Errore","Loop"],correct:"Poca interazione utente"},
{question:"Tipo short Java:",options:["-32768 a 32767","0 a 255","Errore","Illimitato"],correct:"-32768 a 32767"},
{question:"Variabili statiche:",options:["Condivise tra oggetti","Singole","Locali","Errore"],correct:"Condivise tra oggetti"},
{question:"Override:",options:["Ridefinire metodo","Creare metodo","Errore","Loop"],correct:"Ridefinire metodo"},
{question:"Overload:",options:["Stesso nome metodi diversi","Override","Errore","Loop"],correct:"Stesso nome metodi diversi"},
{question:"for loop:",options:["Ripetizione codice","Errore","Classe","Metodo"],correct:"Ripetizione codice"},
{question:"Diagramma classi:",options:["Struttura oggetti","Comportamento","Memoria","Errore"],correct:"Struttura oggetti"},
{question:"Diagramma sequenza:",options:["Interazioni oggetti","Classi","DB","Errore"],correct:"Interazioni oggetti"}
];
